services:
  backend:
    image: ghcr.io/rezafauzan/huawei-backend-technical-test:latest
    container_name: huawei-backend
    restart: unless-stopped
    ports:
      - "8888:8888"

  frontend:
    image: ghcr.io/rezafauzan/huawei-frontend-technical-test:latest
    container_name: huawei-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend