services:
  backend:
    image: ghcr.io/rezafauzan/huawei-backend-technical-test:latest
    container_name: huawei-backend
    restart: unless-stopped
    environment:
      APP_ENV: development
      DEBUG: "true"
      PORT: 8888
      FRONTEND_URL: http://localhost:3000
    ports:
      - "8888:8888"

  frontend:
    image: ghcr.io/rezafauzan/huawei-frontend-technical-test:latest
    container_name: huawei-frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:8888
    ports:
      - "3000:3000"
    depends_on:
      - backend
